Added Social media login.
WongNung/WongNung pull request #53
Opened 2022-11-10 07:15 UTC by Tanabodee-Yambangyang

2022-11-10 07:16 UTC, Supakrit65 approved these changes
**look nice**

2022-11-10 07:18 UTC, GToidZ requested changes
There are duplicate entries in `urls.py` please fix or apply suggestions before merging.

2022-11-10 07:18 UTC, GToidZ commented on pdtx/urls.py
>      path("accounts/", include("django.contrib.auth.urls")),
Delete this line.
```suggestion

```

2022-11-10 07:18 UTC, GToidZ commented on pdtx/urls.py
> +    path('', TemplateView.as_view(template_name="registration/login.html")),
Also, delete this line.
```suggestion

```

2022-11-10 07:19 UTC, GToidZ commented on pdtx/urls.py
> +from django.views.generic import TemplateView
This import is not required.
```suggestion

```

2022-11-10 07:28 UTC, GToidZ approved these changes

2022-11-10 07:35 UTC, Savetang19 approved these changes
It's OK to merge!!!

2022-11-10 07:35 UTC, merged

2022-11-12 09:49 UTC, GToidZ commented
![](https://github.trello.services/images/mini-trello-icon.png) [Backend: OAuth](https://trello.com/c/XxptFsum/51-backend-oauth)